# Generated by Django 2.1.7 on 2022-09-12 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220912_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 12, 18, 10, 28, 334622)),
        ),
    ]
